ALTER TYPE "WebsiteEventType" ADD VALUE IF NOT EXISTS 'ONBOARDING_COMPANY_COMPLETED';
ALTER TYPE "WebsiteEventType" ADD VALUE IF NOT EXISTS 'STRIPE_CHECKOUT_STARTED';
ALTER TYPE "WebsiteEventType" ADD VALUE IF NOT EXISTS 'STRIPE_CHECKOUT_COMPLETED';
ALTER TYPE "WebsiteEventType" ADD VALUE IF NOT EXISTS 'STRIPE_CHECKOUT_FAILED';

ALTER TABLE "WebsiteEvent"
  ADD COLUMN IF NOT EXISTS "utmContent" TEXT,
  ADD COLUMN IF NOT EXISTS "utmTerm" TEXT,
  ADD COLUMN IF NOT EXISTS "consentAnalytics" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "visitorId" TEXT;

ALTER TABLE "DemoLead"
  ADD COLUMN IF NOT EXISTS "utmContent" TEXT,
  ADD COLUMN IF NOT EXISTS "utmTerm" TEXT,
  ADD COLUMN IF NOT EXISTS "visitorId" TEXT,
  ADD COLUMN IF NOT EXISTS "sessionId" TEXT;

CREATE INDEX IF NOT EXISTS "WebsiteEvent_visitorId_createdAt_idx" ON "WebsiteEvent"("visitorId", "createdAt");
CREATE INDEX IF NOT EXISTS "WebsiteEvent_sessionId_createdAt_idx" ON "WebsiteEvent"("sessionId", "createdAt");
