-- A cursor records the current settings version and the next local report slot
-- for each tenant. Existing tenants are initialized lazily by the cron worker;
-- no historical report is generated by this migration.
CREATE TABLE "ScheduledReportCursor" (
    "tenantId" TEXT NOT NULL,
    "settingsAuditLogId" TEXT NOT NULL,
    "timeZone" VARCHAR(128) NOT NULL,
    "nextRunAt" TIMESTAMP(3),
    "lastQueuedFor" TIMESTAMP(3),
    "lastSkippedFrom" TIMESTAMP(3),
    "lastSkippedThrough" TIMESTAMP(3),
    "lastSkipReason" VARCHAR(64),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ScheduledReportCursor_pkey" PRIMARY KEY ("tenantId")
);

CREATE INDEX "ScheduledReportCursor_nextRunAt_idx" ON "ScheduledReportCursor"("nextRunAt");

ALTER TABLE "ScheduledReportCursor"
ADD CONSTRAINT "ScheduledReportCursor_tenantId_fkey"
FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
